image: node:latest
variables:
  # overlay2 driver, speed it up
  DOCKER_DRIVER: overlay2

# define cache here, to share over all stages
cache:
  key: "$CI_COMMIT_REF_NAME"
  untracked: true
  paths:
    - node_modules/

stages: [build, test, staging, deploy]

setup_js:
  stage: build
  script:
    - yarn add sass
    - yarn install
  only:
    - master
  tags:
    - docker

test_js:
  stage: test
  dependencies:
  - setup_js
  script:
    - yarn test
  only:
    - master
  tags:
    - docker

pages:
  stage: deploy
  dependencies:
  - setup_js
  script:
    - yarn build
  # - mkdir .public
  # - cp -r * .public
    - mv dist public  # only public folder will be shown in pages ;-)
  artifacts:
    expire_in: 72h
    when: on_success
    paths:
    - public
  only:
    - master
