image: node:latest

cache:
  paths:
    - node_modules/

stages: [build, test, staging, deploy]

setup_js:
  stage: build
  script:
    - npm install sass
    - npm install
  # artifacts:
  #   expire_in: 72h
  #   when: on_success
  #   paths:
  #     - node_modules/
  only:
    - master
  tags:
    - docker

test_js:
  stage: test
  dependencies:
  - setup_js
  script:
    - npm test
  only:
    - master
  tags:
    - docker

pages:
  stage: deploy
  dependencies:
  - setup_js
  script:
    - yarn build
  # - mkdir .public
  # - cp -r * .public
    - mv dist public
  artifacts:
    expire_in: 72h
    when: on_success
    paths:
    - dist
  only:
    - master
