version: "3.6"

services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: 'gitlab'
    hostname: gitlab.example.com
    volumes: ["gitlab-config:/etc/gitlab", "gitlab-logs:/var/log/gitlab", "gitlab-data:/var/opt/gitlab"]
    ports: ["443", "1000:80", "81:81", "2222:22", "4567:4567"]
    restart: always
    networks:
      - gitlab-network
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        ## GitLab URL
        ##! URL on which GitLab will be reachable.
        external_url 'http://gitlab.example.com'
        ################################################################################
        ## gitlab.yml configuration
        ##! Docs: https://gitlab.com/gitlab-org/omnibus-gitlab/blob/master/doc/settings/gitlab.yml.md
        ################################################################################
        gitlab_rails['gitlab_ssh_host'] = 'ssh.gitlab.example.com'
        gitlab_rails['time_zone'] = 'UTC'
        ################################################################################
        ## Container Registry settings
        ##! Docs: https://docs.gitlab.com/ce/administration/container_registry.html
        ################################################################################
        registry_external_url 'http://registry.gitlab.example.com'
        ################################################################################
        ## GitLab Pages
        ##! Docs: https://docs.gitlab.com/ce/pages/administration.html
        ################################################################################
        gitlab_pages['enable'] = true
        pages_nginx['enable'] = false
        # gitlab_pages['external_http'] = 'http://pages.example.com/'
        gitlab_pages['external_http'] = ['http://gitlab:81']
        pages_external_url 'http://pages.example.com/'
        gitlab_pages['inplace_chroot'] = true
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: 'gitlab-runner'
    volumes: ["gitlab-runner-config:/etc/gitlab-runner:Z", "/var/run/docker.sock:/var/run/docker.sock"]
    hostname: gitlab-runner.example.com
    depends_on:
      - gitlab
    networks:
      - gitlab-network

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  gitlab-runner-config:

networks:
  gitlab-network:
    name: gitlab-network
